import{S as w,i as u,a as q}from"./assets/vendor-5401a4b0.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const P=new w(".photo-container a",{captionsData:"alt",captionDelay:250}),E=document.querySelector(".search-form"),p=document.querySelector(".photo-list"),n=document.querySelector('[data-action="load-more"]'),m=document.querySelector(".loader"),h=document.querySelector(".loader-load-more"),o="is-hidden";let l="",d=1,y=0;const f=40,$="https://pixabay.com/api",M="41870399-9b44301246ceb98c07efd626a";E.addEventListener("submit",O);async function O(a){a.preventDefault(),p.innerHTML="",m.classList.remove(o),d=1;const t=a.currentTarget;if(l=t.elements.query.value.trim(),!l){m.classList.add(o),n.classList.add(o),u.show({message:"Please enter your request",position:"topRight",color:"yellow"});return}try{const{hits:s,totalHits:i}=await g(l);y=Math.ceil(i/f),b(s,p),s.length>0&&s.length!==i?(n.classList.remove(o),n.addEventListener("click",L)):s.length?n.classList.add(o):(n.classList.add(o),u.show({message:"Sorry, there are no images matching your search query. Please try again!",position:"center",color:"red"}))}catch(s){console.log(s)}finally{m.classList.add(o),t.reset()}}async function g(a,t=1){try{return(await q.get(`${$}/`,{params:{key:M,q:a,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:f,page:t}})).data}catch{u.error({title:"Error",position:"center",color:"red",message:"Sorry! Try later! Server not working"}),console.error(error.message)}}async function L(){d+=1,h.classList.remove(o),n.classList.add(o);const a=document.querySelector(".gallery-item").getBoundingClientRect();try{const{hits:t}=await g(l,d);b(t,p)}catch(t){console.log(t)}finally{window.scrollBy({top:a.height*2,left:0,behavior:"smooth"}),h.classList.add(o),n.classList.remove(o),d===y&&(n.classList.add(o),n.removeEventListener("click",L),u.show({color:"blue",position:"bottomCenter",message:"We're sorry, but you've reached the end of search results."}))}}function b(a){const t=a.map(({webformatURL:s,largeImageURL:i,tags:e,likes:r,views:c,comments:v,downloads:S})=>`<li class="gallery-item">
  <a class="gallery-link" href="${i}">
    <img
      class="gallery-image"
      src="${s}"
      alt="${e}"
    />
  </a><div class="gallery-descr">
   <p>Likes: <br><span>${r}</span></p>
   <p>Views: <br><span>${c}</span></p>
   <p>Comment: <br><span>${v}</span></p>
   <p>Downloads: <br><span>${S}</span></p></div>
</li>`).join("");p.insertAdjacentHTML("beforeend",t),P.refresh()}
//# sourceMappingURL=commonHelpers.js.map
